# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:37"
      timezone: "Asia/Kolkata"
    registries:
      - nvcr-repo

registries:
  nvcr-repo:
   type: "docker-registry"
   url: "https://nvcr.io"
   username: ${{ secrets.REGISTRY_USER }}
   password: ${{ secrets.REGISTRY_PASSWORD }}
