name: Renovate

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   # - cron: "*/15 * * * *"
  #    - cron: "0 0 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v32.169.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          LOG_LEVEL: debug
          RENOVATE_LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: '["shivakunv/gpu-operator-shiva"]'
          # RENOVATE_ONBOARDING: false
          DEBUG: hostRules,config,docker
          RENOVATE_DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          RENOVATE_DOCKER_USERNAME: '$oauthtoken'
          RENOVATE_DOCKER_REGISTRY_URL: 'nvcr.io'
