name: Renovate

on:
  workflow_dispatch:
  schedule:
    # - cron: "*/15 * * * *"
     - cron: "0 0 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          RENOVATE_CONFIG_FILE: .github/renovate.json
