name: Renovate

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   # - cron: "*/15 * * * *"
  #    - cron: "0 0 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.2
        with:
          configurationFile: .github/renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          LOG_LEVEL: debug
          RENOVATE_LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: '["shivakunv/gpu-operator-shiva"]'
          # RENOVATE_ONBOARDING: false
          DEBUG: hostRules,config,docker
