name: Renovate

on:
  workflow_dispatch:
  schedule:
     - cron: "0 0 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.2
        with:
          configurationFile: .github/renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
          RENOVATE_LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: '["shivakunv/gpu-operator-shiva"]'
          DEBUG: hostRules,config,docker
          
